name: BuildAndPublish

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'dotnet-procstoclasses.sln'
      MAIN_PROJECT: 'dotnet-procstoclasses'
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        with: 
          nuget-version: latest

      - name: Restore dependencies
        working-directory: ./Source/dotnet-procstoclasses
        run: nuget restore $MAIN_PROJECT

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.*

      - name: Build
        working-directory: ./Source/dotnet-procstoclasses
        run: dotnet build $MAIN_PROJECT --configuration $BUILD_CONFIG --no-restore

      - name: Push to nuget
        working-directory: ./Source/dotnet-procstoclasses
        run: dotnet nuget push **/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}        
