name: Build

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'dotnet-procstoclasses.sln'
      MAIN_PROJECT: 'dotnet-procstoclasses.csproj'
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        with: 
          nuget-version: latest

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.*

      - name: Restore dependencies
        working-directory: ./Source/dotnet-procstoclasses
        run: dotnet restore $MAIN_PROJECT

      - name: Build
        working-directory: ./Source/dotnet-procstoclasses
        run: dotnet build $MAIN_PROJECT --configuration $BUILD_CONFIG --no-restore
